<?php

// @codingStandardsIgnoreFile

/** @var \M2E\OnBuy\Block\Adminhtml\Wizard\InstallationOnBuy\Installation\ListingTutorial\Content $block */

?>

<div class="wizard_block">
    <h2>
        <?= __('Congratulations! You have registered your M2E OnBuy Connect Extension and linked ' .
            'your OnBuy Account to it.'); ?>
    </h2>

    <p>
        <?= __('The next step involves creating your first M2E OnBuy Connect Listing.'); ?>
    </p>
    <br/>

    <p>
        <?= __('M2E OnBuy Connect Listing is a group of Magento Products combined under specific sets ' .
            'of rules. <br/>These are the Products which will be offered as OnBuy Items by a Seller on ' .
            'a particular Shop.'); ?>
    </p>
    <br/>

    <p>
        <?= __('Click on the <strong>Create First Listing</strong> button to proceed. Or click on ' .
            'the <strong>Skip</strong> button if you want to create your first listing later.'); ?>
    </p>
</div>
