<?php

/** @var \M2E\OnBuy\Block\Adminhtml\Template\Category\Chooser\Tabs\Browse $block */

$isWizard = !$block->viewHelper->isInstallationWizardFinished();

$block->jsUrl->add($block->getUrl('*/general/getChildCategories'), 'general/getChildCategories');

$block->js->add(
    "
require([
    'OnBuy/Template/Category/Chooser/Tabs/Browse'
], function(){

    window.OnBuyTemplateCategoryChooserTabsBrowseObj = new OnBuyTemplateCategoryChooserTabsBrowse();

    OnBuyTemplateCategoryChooserTabsBrowseObj.setSiteId(OnBuyCategoryChooserObj.getSiteId());
    OnBuyTemplateCategoryChooserTabsBrowseObj.setAccountId(OnBuyCategoryChooserObj.getAccountId());
    OnBuyTemplateCategoryChooserTabsBrowseObj.renderTopLevelCategories('chooser_browser-selects');
    OnBuyTemplateCategoryChooserTabsBrowseObj.observe('leaf_selected', function(selectedCategories) {
        const lastCategory = selectedCategories[selectedCategories.length-1];
        OnBuyCategoryChooserObj.selectCategory(lastCategory['value']);
    });
});

"
);
?>

<style>
    .category-children-block {
        display: inline-block;
        margin-left: 10px;
    }
</style>

<div id="chooser_browser">
    <div id="chooser_browser-selects"></div>
</div>
